# Used for pure development purposes. All accounts are simulated using the Loopback Link.
# See https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties
spring:
  profiles:
    include: h2, management, jks

interledger:
  connector:
    connector-url: http://localhost:8080
    admin-password: admin:password
  # SPSP settings below are used to create new accounts on the Connector so that they forward and route proplery to
  # the remote SPSP server.
  spsp:
    spsp-url: http://localhost:8080
    auth-token: placeholder:c2ho
    address-prefix: test1.connie

grpc:
  enableReflection: true
