# Used for pure development purposes. All accounts are simulated using the Loopback Link.
# See https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties
spring:
  profiles:
    include: h2, management

interledger:
  connector:
    connector-url: http://localhost:8080
  spsp:
    spsp-url: https://money.ilpv4.dev
    auth-token: placeholder:c2ho
    address-prefix: test.jc.money

grpc:
  port: 6565
  enableReflection: true
