# Used for pure development purposes. All accounts are simulated using the Loopback Link.
# See https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties
spring:
  profiles:
    include: h2, management

interledger:
  connector:
    connector-url: http://localhost:18080

grpc:
  port: 6565
  enableReflection: true
